name: CI
on:
  pull_request:
    branches: [ "main" ]
  push:
    tags: ["*"]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest-8c32g
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_IO_BOT_USERNAME }}
          password: ${{ secrets.QUAY_IO_BOT_PASSWORD }}
          registry: quay.io

      - uses: olegtarasov/get-tag@v2.1
        id: tag-name

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod

      - name: download server package
        run: go mod download -x

      - name: Test
        run: |
          go test -v ./...

      - name: build server
        run: make build

      - name: Build and publish tag docker image
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          context: .
          push: true
          tags: quay.io/subscan-explorer/solidity-verification-tool:${{ env.GIT_TAG_NAME }}
          labels: ${{ steps.meta.outputs.labels }}